### ISSUE TITLE
SSAO is not applied to units which use ZK CUS

### ISSUE THREAD

**Issue by GoogleFrog** [lhog/spring-ssao#1]
I've noticed that SSAO doesn't affect units with normalmapping (the common use for CUS in ZK). Two units to compare are Redback and Recluse.

**Comment by lhog** [comment]
That's because ZK normalmapping CUS material doesn't use deferred rendering path:
https://github.com/ZeroK-RTS/Zero-K/blob/master/ModelMaterials/1_normalmapping.lua#L10
Equally such units are not affected by dynamic deferred lights system.

You might want to make material file look like this in order to enable deferred shading: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/materials/1_normalmapping.lua#L17-L30
